name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Node install dependencies
      run: npm install
    - name: SonarCloud Scan
      # You may pin to the exact commit or the version.
      # uses: SonarSource/sonarcloud-github-action@cb201f3b2d7a38231a8c042dfea4539c8bea180b.
      uses: SonarSource/sonarcloud-github-action@v1.8
      with:
        # Additional arguments to the sonarcloud scanner
        args: -Dsonar.organization=wilmeram10 -Dsonar.projectKey=final-API-REST -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_API }}
